# Generated by Django 3.0.3 on 2020-07-24 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyTable',
            fields=[
                ('primary_key', models.IntegerField(primary_key=True, serialize=False)),
                ('times', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Table1',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('property_one', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_two', models.IntegerField()),
                ('foreign_primary_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_primary_key', to='app.Table1')),
                ('foreign_property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foreign_property', to='app.Table1', to_field='property_one')),
            ],
        ),
    ]
