# Generated by Django 3.0.3 on 2020-07-24 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table2',
            name='id',
        ),
        migrations.AlterField(
            model_name='table2',
            name='foreign_primary_key',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='foreign_primary_key', serialize=False, to='app.Table1'),
        ),
    ]
